version: '3.8'
services:
  stats-server:
    build: ./stats
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsdb
      - SPRING_DATASOURCE_PASSWORD=statsdb

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stat
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=statsdb
      - POSTGRES_USER=statsdb
      - POSTGRES_DB=statsdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/maindb
      - SPRING_DATASOURCE_USERNAME=maindb
      - SPRING_DATASOURCE_PASSWORD=maindb
      - STATSERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:14-alpine
    container_name: postgres-main
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=maindb
      - POSTGRES_USER=maindb
      - POSTGRES_DB=maindb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10