DROP TABLE IF EXISTS endpoint_requests CASCADE;
CREATE TABLE IF NOT EXISTS endpoint_requests (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER SEQUENCE endpoint_requests_id_seq RESTART WITH 1;